spring.application.name=city-weather
countrylayer.base-url=https://api.countrylayer.com/v2
countrylayer.api-key=3c7143d6ac21b5839a8eecf5dbdb22b9
weatherLayer.base-url=https://api.openweathermap.org/data/2.5/
weatherLayer.api-key=b6946a3823982b6fb81f26a0d8293e40

